
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies
      - python -m pip install --upgrade pip
      - pip install flake8 pytest
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - pip install tabulate
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling Python code
  post_build:
    commands:
      - echo Build completed on `date`